# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import store_pb2 as store__pb2


class StoreStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.price = channel.unary_unary(
                '/Store/price',
                request_serializer=store__pb2.price_request.SerializeToString,
                response_deserializer=store__pb2.price_response.FromString,
                )
        self.sale = channel.unary_unary(
                '/Store/sale',
                request_serializer=store__pb2.sale_request.SerializeToString,
                response_deserializer=store__pb2.sale_response.FromString,
                )
        self.end_of_work_store = channel.unary_unary(
                '/Store/end_of_work_store',
                request_serializer=store__pb2.end_of_work_store_request.SerializeToString,
                response_deserializer=store__pb2.end_of_work_store_response.FromString,
                )


class StoreServicer(object):
    """Missing associated documentation comment in .proto file."""

    def price(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def sale(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def end_of_work_store(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'price': grpc.unary_unary_rpc_method_handler(
                    servicer.price,
                    request_deserializer=store__pb2.price_request.FromString,
                    response_serializer=store__pb2.price_response.SerializeToString,
            ),
            'sale': grpc.unary_unary_rpc_method_handler(
                    servicer.sale,
                    request_deserializer=store__pb2.sale_request.FromString,
                    response_serializer=store__pb2.sale_response.SerializeToString,
            ),
            'end_of_work_store': grpc.unary_unary_rpc_method_handler(
                    servicer.end_of_work_store,
                    request_deserializer=store__pb2.end_of_work_store_request.FromString,
                    response_serializer=store__pb2.end_of_work_store_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Store', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Store(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def price(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Store/price',
            store__pb2.price_request.SerializeToString,
            store__pb2.price_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def sale(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Store/sale',
            store__pb2.sale_request.SerializeToString,
            store__pb2.sale_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def end_of_work_store(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Store/end_of_work_store',
            store__pb2.end_of_work_store_request.SerializeToString,
            store__pb2.end_of_work_store_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
