# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: store.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bstore.proto\"\x0f\n\rprice_request\"%\n\x0eprice_response\x12\x13\n\x0bprice_value\x18\x01 \x01(\x05\"\'\n\x0csale_request\x12\x17\n\x0ftransaction_key\x18\x01 \x01(\x0c\"\x1f\n\rsale_response\x12\x0e\n\x06status\x18\x01 \x01(\x05\"\x1b\n\x19\x65nd_of_work_store_request\",\n\x1a\x65nd_of_work_store_response\x12\x0e\n\x06status\x18\x01 \x01(\x05\x32\xac\x01\n\x05Store\x12*\n\x05price\x12\x0e.price_request\x1a\x0f.price_response\"\x00\x12\'\n\x04sale\x12\r.sale_request\x1a\x0e.sale_response\"\x00\x12N\n\x11\x65nd_of_work_store\x12\x1a.end_of_work_store_request\x1a\x1b.end_of_work_store_response\"\x00\x62\x06proto3')



_PRICE_REQUEST = DESCRIPTOR.message_types_by_name['price_request']
_PRICE_RESPONSE = DESCRIPTOR.message_types_by_name['price_response']
_SALE_REQUEST = DESCRIPTOR.message_types_by_name['sale_request']
_SALE_RESPONSE = DESCRIPTOR.message_types_by_name['sale_response']
_END_OF_WORK_STORE_REQUEST = DESCRIPTOR.message_types_by_name['end_of_work_store_request']
_END_OF_WORK_STORE_RESPONSE = DESCRIPTOR.message_types_by_name['end_of_work_store_response']
price_request = _reflection.GeneratedProtocolMessageType('price_request', (_message.Message,), {
  'DESCRIPTOR' : _PRICE_REQUEST,
  '__module__' : 'store_pb2'
  # @@protoc_insertion_point(class_scope:price_request)
  })
_sym_db.RegisterMessage(price_request)

price_response = _reflection.GeneratedProtocolMessageType('price_response', (_message.Message,), {
  'DESCRIPTOR' : _PRICE_RESPONSE,
  '__module__' : 'store_pb2'
  # @@protoc_insertion_point(class_scope:price_response)
  })
_sym_db.RegisterMessage(price_response)

sale_request = _reflection.GeneratedProtocolMessageType('sale_request', (_message.Message,), {
  'DESCRIPTOR' : _SALE_REQUEST,
  '__module__' : 'store_pb2'
  # @@protoc_insertion_point(class_scope:sale_request)
  })
_sym_db.RegisterMessage(sale_request)

sale_response = _reflection.GeneratedProtocolMessageType('sale_response', (_message.Message,), {
  'DESCRIPTOR' : _SALE_RESPONSE,
  '__module__' : 'store_pb2'
  # @@protoc_insertion_point(class_scope:sale_response)
  })
_sym_db.RegisterMessage(sale_response)

end_of_work_store_request = _reflection.GeneratedProtocolMessageType('end_of_work_store_request', (_message.Message,), {
  'DESCRIPTOR' : _END_OF_WORK_STORE_REQUEST,
  '__module__' : 'store_pb2'
  # @@protoc_insertion_point(class_scope:end_of_work_store_request)
  })
_sym_db.RegisterMessage(end_of_work_store_request)

end_of_work_store_response = _reflection.GeneratedProtocolMessageType('end_of_work_store_response', (_message.Message,), {
  'DESCRIPTOR' : _END_OF_WORK_STORE_RESPONSE,
  '__module__' : 'store_pb2'
  # @@protoc_insertion_point(class_scope:end_of_work_store_response)
  })
_sym_db.RegisterMessage(end_of_work_store_response)

_STORE = DESCRIPTOR.services_by_name['Store']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PRICE_REQUEST._serialized_start=15
  _PRICE_REQUEST._serialized_end=30
  _PRICE_RESPONSE._serialized_start=32
  _PRICE_RESPONSE._serialized_end=69
  _SALE_REQUEST._serialized_start=71
  _SALE_REQUEST._serialized_end=110
  _SALE_RESPONSE._serialized_start=112
  _SALE_RESPONSE._serialized_end=143
  _END_OF_WORK_STORE_REQUEST._serialized_start=145
  _END_OF_WORK_STORE_REQUEST._serialized_end=172
  _END_OF_WORK_STORE_RESPONSE._serialized_start=174
  _END_OF_WORK_STORE_RESPONSE._serialized_end=218
  _STORE._serialized_start=221
  _STORE._serialized_end=393
# @@protoc_insertion_point(module_scope)
